### PR TITLE
Issue #76: fix wire type checking for packed repeated fields

### PR DESCRIPTION
**Pull request by knoguchi**
Fixed the isValidFor method.  The deserializing of the repeated field to an array seems to be fine.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Sounds reasonable, but would it be possible to have a test case? This would help against regression.

**Comment by knoguchi** [comment]
Added the test case.   Currently Travis fails for the master branch.   An Avro test case is failing but that's nothing to do with my change.

**Comment by cowtowncoder** [comment]
Ok I had accidentally added failing avro test under other tests, not under `failing`; moved so it won't block builds.

**Comment by cowtowncoder** [comment]
Ok I'm happy to merge this fix (and related) test. Just one thing before merging the contribution; if we haven't yet asked, we'd need a Contributor License Agreement (CLA):

     https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

and the easiest way is often to just print, fill & sign, scan, email to `info` at fasterxml dot com.
If that could be done I'd be happy to merge this and then tackle encoding side.

Thank you in advance!

**Comment by knoguchi** [comment]
I've signed and sent the CLA as instructed.    Thank you.

**Comment by cowtowncoder** [comment]
@knoguchi For some reason I don't seem to have that... will try to check my inbox at fasterxml (I get `info` forward to my account).

**Pull request merged**
